# Generated by Django 5.0.14 on 2025-09-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='registration_deadline',
            field=models.DateField(blank=True, help_text='The last date for student registration.', null=True),
        ),
    ]
