# Generated by Django 5.0.14 on 2025-10-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_university_registration_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='alumni',
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('image', models.ImageField(upload_to='alumni_photos/')),
                ('current_company', models.CharField(blank=True, max_length=100)),
                ('current_position', models.CharField(blank=True, max_length=100)),
                ('testimonial', models.TextField(blank=True)),
                ('linkedin_profile_url', models.URLField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='core.university')),
            ],
        ),
    ]
